components:
  ingressGateways:
    - enabled: true
      name: istio-ingressgateway
  pilot:
    enabled: true

global:
  hub: docker.io/istio
  tag: 1.22.0

meshConfig:
  enablePrometheusMerge: true
  defaultProviders:
    metrics:
      - prometheus

telemetry:
  metrics:
    enabled: true
    metrics:
      providers:
        - name: prometheus
    overrides:
    - match:
        metric: ALL_METRICS
      tagOverrides:
        # ✅ Keep these 10
        source_app:
          operation: KEEP
        destination_app:
          operation: KEEP
        destination_workload:
          operation: KEEP
        destination_workload_namespace:
          operation: KEEP
        destination_service:
          operation: KEEP
        reporter:
          operation: KEEP
        request_protocol:
          operation: KEEP
        response_code:
          operation: KEEP
        security_istio_io_tlsMode:
          operation: KEEP
        connection_security_policy:
          operation: KEEP

        # ❌ Remove everything else
        source_version:
          operation: REMOVE
        source_workload:
          operation: REMOVE
        source_workload_namespace:
          operation: REMOVE
        source_canonical_service:
          operation: REMOVE
        source_canonical_revision:
          operation: REMOVE
        source_principal:
          operation: REMOVE
        destination_service_name:
          operation: REMOVE
        destination_service_namespace:
          operation: REMOVE
        destination_version:
          operation: REMOVE
        destination_canonical_service:
          operation: REMOVE
        destination_canonical_revision:
          operation: REMOVE
        destination_principal:
          operation: REMOVE
        response_code_details:
          operation: REMOVE
        response_flags:
          operation: REMOVE

