# Minimal Istio installation
global:
  hub: "docker.io/istio"

# Install only istiod (control plane) + ingress
components:
  pilot:
    enabled: true
  ingressGateways:
    - name: istio-ingressgateway
      enabled: true
  egressGateways:
    - name: istio-egressgateway
      enabled: false

# Resource settings for istiod
pilot:
  resources:
    requests:
      cpu: "500m"
      memory: "2048Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"

# Mesh config overrides
meshConfig:
  defaultConfig:
    proxyMetadata: {}
  enablePrometheusMerge: true

