apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-addresspool
  namespace: metallb-system
spec:
  addresses:
    - 172.168.122.29-172.168.122.31
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-l2adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - default-addresspool

