apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/releases/download/v1.13.0/cluster-template.yaml
patches:
- path: ../patches/azuremachinetemplate-controlplane.yaml
- path: ../patches/azuremachinetemplate-workload.yaml
