# Copyright 2024 The Kubernetes Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Install Azure CLI
  when: ansible_os_family == "Debian"
  block:
    - name: Add Microsoft Package Repository Key
      ansible.builtin.apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Find Ubuntu Version
      ansible.builtin.command:
        cmd: lsb_release -cs
      register: ubuntu_version
      changed_when: false

    - name: Find Host Architecture
      ansible.builtin.command:
        cmd: dpkg --print-architecture
      register: host_arch
      changed_when: false

    - name: Add Microsoft Package Repository
      ansible.builtin.apt_repository:
        repo: 'deb [arch={{ host_arch.stdout }}] https://packages.microsoft.com/repos/azure-cli/ {{ ubuntu_version.stdout }} main'
        state: present
        update_cache: true

    - name: Install Azure CLI
      ansible.builtin.apt:
        name: azure-cli
        state: present

- name: Install Azure CLI
  when: ansible_os_family in ["Common Base Linux Mariner", "Microsoft Azure Linux"]
  ansible.builtin.package:
    name: azure-cli
    state: present

- name: Install Azure CLI
  when: ansible_os_family == "RedHat"
  block:
    - name: Import the Microsoft repository key
      ansible.builtin.rpm_key:
        key: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add the yum repository for the azure cli
      ansible.builtin.yum_repository:
        name: azure_cli
        description: Azure CLI
        baseurl: https://packages.microsoft.com/yumrepos/azure-cli
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        gpgcheck: true
        enabled: true

    - name: Install Azure CLI
      ansible.builtin.package:
        name: azure-cli
        state: present
