- name: Include QEMU tasks
  ansible.builtin.include_tasks: qemu.yml

- name: Include MaaS Specific configs for Ubuntu Distro
  ansible.builtin.include_tasks: maas-ubuntu.yml
  when: ansible_os_family == "Debian"
