---
- name: Install cloud-init packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: true
  vars:
    packages:
      - cloud-init
      - cloud-guest-utils
      - cloud-initramfs-copymods
      - cloud-initramfs-dyn-netconf
