istio:
  version: 1.25.3   

global:
  hub: docker.io/istio
  tag: 1.25.3
  proxy:
    autoInject: enabled   

pilot:
  autoscaleEnabled: true


gateways:
  istio-ingressgateway:
    name: istio-ingressgateway
    type: NodePort

meshConfig:
  defaultProviders:
    metrics:
      - prometheus
  telemetry:
    metrics:
      overrides:
        - match:
            metric: ALL_METRICS
          tagOverrides:
            destination_service:
              operation: KEEP
            destination_service_name:
              operation: KEEP
            destination_service_namespace:
              operation: KEEP
            destination_app:
              operation: KEEP
            source_app:
              operation: KEEP
            source_workload:
              operation: KEEP
            source_workload_namespace:
              operation: KEEP
            request_protocol:
              operation: KEEP
            response_code:
              operation: KEEP
            grpc_response_status:
              operation: KEEP
            response_flags:
              operation: KEEP
            reporter:
              operation: KEEP
            connection_security_policy:
              operation: KEEP
            tls_version:
              operation: KEEP
            tcp_connection_closed:
              operation: KEEP

            destination_version:
              operation: REMOVE
            source_version:
              operation: REMOVE
            destination_principal:
              operation: REMOVE
            source_principal:
              operation: REMOVE
            kubernetes_pod_name:
              operation: REMOVE
