---
# TODO: This task will be deprecated once https://github.com/containerd/cri/issues/1131 is fixed
- name: Create kubeadm config file
  ansible.builtin.template:
    dest: /etc/kubeadm.yml
    src: etc/kubeadm.yml
    mode: "0600"

- name: Get images list
  ansible.builtin.shell: kubeadm config images list --config /etc/kubeadm.yml
  register: images_list

- name: Log into ECR
  ansible.builtin.command: >
    aws ecr get-authorization-token
    --registry-ids {{ kubernetes_container_registry.split('.')[0] }}
    --region {{ kubernetes_container_registry.split('.')[3] }}
    --output text
    --query 'authorizationData[].authorizationToken'
  register: credentials

- name: Pull images
  ansible.builtin.command: crictl pull --creds {{ credentials.stdout | b64decode }} {{ item }}
  loop: "{{ images_list.stdout_lines }}"

- name: Delete kubeadm config
  ansible.builtin.file:
    path: /etc/kubeadm.yml
    state: absent
  when: ansible_os_family != "Flatcar"
