- name: Update apt cache
  apt:
    update_cache: yes
- name: Install yq
  shell: |
    wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
    chmod +x /usr/local/bin/yq
  args:
    creates: /usr/local/bin/yq

- name: Install required dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - jq
      - fping
    state: present

- name: Install Docker
  apt:
    name: docker.io
    state: present
  notify:
    - Start Docker

- name: Install kubectl
  shell: |
    curl -LO "https://dl.k8s.io/release/{{ KUBECTL_VERSION }}/bin/linux/amd64/kubectl"
    mv ./kubectl /usr/local/bin/kubectl
    chmod +x /usr/local/bin/kubectl
  args:
    creates: /usr/local/bin/kubectl

- name: Install kind
  shell: |
    curl -Lo ./kind "https://github.com/kubernetes-sigs/kind/releases/download/{{ KIND_VERSION }}/kind-linux-amd64"
    mv ./kind /usr/local/bin/kind
    chmod +x /usr/local/bin/kind
  args:
    creates: /usr/local/bin/kind

- name: Install eksctl
  shell: |
    curl --silent --location "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz" | tar xz -C /tmp
    mv /tmp/eksctl /usr/local/bin/eksctl
    chmod +x /usr/local/bin/eksctl
  args:
    creates: /usr/local/bin/eksctl

# Install eksctl-anywhere
- name: Install eksctl-anywhere
  shell: |
    URL=$(curl  -s https://anywhere-assets.eks.amazonaws.com/releases/eks-a/manifest.yaml | grep {{ EKSCTL_PLUGIN_VERSION }} | grep linux-amd64 | head -1 |awk '{print $2}')
    curl --silent --location "$URL" | tar xz ./eksctl-anywhere
    mv  ./eksctl-anywhere  /usr/local/bin/
  args:
    creates: /usr/local/bin/eksctl-anywhere
  tags: install

- name: Add user to groups
  user:
    name: "{{ ADMIN_USER }}"
    groups:
      - sudo
      - docker
    append: yes

- name: Install AZ CLI
  shell: curl -sL https://aka.ms/InstallAzureCLIDeb | bash
  args:
    creates: /usr/bin/az

- name: Install temporal CLI
  shell: |
    wget -O temporal-cli.tar.gz "https://temporal.download/cli/archive/latest?platform=linux&arch=amd64"
    tar xf temporal-cli.tar.gz
    chmod +x temporal
    mv temporal /usr/local/bin/
    rm -f temporal-cli.tar.gz
  args:
    creates: /usr/local/bin/temporal

- name: Install Racadm
  shell: |
    wget  https://armadaosimages.blob.core.windows.net/packages/srvadmin-hapi_11.0.0.0_amd64.deb
    apt install -y srvadmin-hapi_11.0.0.0_amd64.deb 
    wget https://armadaosimages.blob.core.windows.net/packages/srvadmin-idracadm7_11.0.0.0_all.deb
    apt install -y srvadmin-idracadm7_11.0.0.0_all.deb 
    wget https://armadaosimages.blob.core.windows.net/packages/srvadmin-idracadm8_11.0.0.0_amd64.deb
    apt install -y srvadmin-idracadm8_11.0.0.0_amd64.deb
  
