{{- range .Values.ChartName }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ . }}
  namespace: argocd
spec:
  project: {{ $.Values.project }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $.Values.namespace }}
  source:
    repoURL: {{ $.Values.repoURL }}
    chart: {{ . }}
    targetRevision: {{ $.Values.version }}
    helm:
      values: |
        {{ toYaml $.Values.valuesObject | indent 8 }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
{{- end }}

